version: '3.8'

services:
  app:
    image: php:8.4.8-cli
    container_name: findenhub_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: sh -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - node

  node:
    image: node:20-alpine
    container_name: findenhub_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run build" 